name: tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: update /etc/hosts
        run: |
          sudo echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
          cat /etc/hosts
      - name: start Redash
        run: |
          cd redash
          ./setup.sh
      - name: run tests
        run: |
          ./support/testing/test.sh ./about
